name: crest
channels:
  - conda-forge
  - bioconda
  - defaults
  - xapple
dependencies:
  - autopaths==1.6.2
  - plumbing==2.11.3
  - fasta==2.3.3
  - seqsearch==2.2.2
  - optmagic==1.1.1
  - biopython==1.86
  - rich==14.2.0
  - pandas==2.3.3
  - pytest==9.0.2
  - pytest-asyncio==1.3.0
  - pip:
      - ete4==4.4.0
