name: Test PyPI release on macOS

# This workflow will install the latest PyPI release of the package (not the
# master branch of the repository) and will run pytest on two python versions.
# It will search both in the real PyPI index and the test PyPI index.

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.14']
        os: [macos-latest]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip itself
        run: python -m pip install --upgrade pip

      - name: Install the package from PyPI
        run: python -m pip install --extra-index-url https://test.pypi.org/simple/ crest4[test]

      - name: Install BLAST and VSEARCH
        run: brew install blast vsearch

      - name: Run the pytest suite
        run: crest4 --pytest